import pandas as pd
import geopandas as gpd
from shapely.geometry import LineString
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import statsmodels.api as sm
import numpy as np
import os

###############################################################################
# NOTE: MANUAL STEPS TAKEN:
    # 1. capture screenshot of Fig. 1a in Zhisheng et al. 2015, "Global Monsoon
    #    Dynamics and Climate Change"
    # 2. go to https://apps.automeris.io/wpd/, click File -> Load Images and upload screenshot
    # 3. select "Map With Scale Bar", click "Align Axes", then drop two points
    #    along the 0-degree meridian (points: (0,0) and (0, 30)

    # 4. click "Complete" and enter '10' and 'degrees' in the prompt boxes

    # 5. click on the color box next to "Foreground color" and select the blue
    #    corresponding to the DJF ITCZ curve

    # 6. set color distance to 20, deltaX and deltaY to 1 pixel, then click
    #    "Run" to add automatically digitized points along the DJF ITCZ curve

    # 7. click "Delete Point (D)", hover over the incorrectly digitized points
    #    added to the map legend, and repeatedly click until the last point
    #    there is deleted

    # 8. click "View Data" -> "Download .CSV" and download the CSV file as
    #    'ITCZ_DJF.csv'

    # 9. repeat steps 5-8 for the JJA ITCZ curve and download its file as
    #    'ITCZ_JJA.csv'

    # 10. run this script to produce the shapefile

###############################################################################

data_dir = ('/home/deth/Desktop/CAL/research/projects/seasonality/'
            'seasonal_asynchrony/analysis')

# read in raw, digitized data for boreal-summer ITCZ
itczJJA = pd.read_csv(os.path.join(data_dir, 'ITCZ_JJA.csv'), header=None)
itczJJA.columns = ['lon', 'lat']
# drop the few points that were digitized to the legend line
# (rather than the actual mapped line)
itczJJA = itczJJA[itczJJA['lat']<140]
# use LOWESS to get rid of the funky strata generated by the plot digitizer
itczJJA.loc[:, :] = sm.nonparametric.lowess(exog=itczJJA['lon'],
                                         endog=itczJJA['lat'],
                                         frac=0.05)

# same for boreal-winter ITCZ
itczDJF = pd.read_csv(os.path.join(data_dir, 'ITCZ_DJF.csv'), header=None)
itczDJF.columns = ['lon', 'lat']
itczDJF = itczDJF[itczDJF['lat']<140]
itczDJF.loc[:, :] = sm.nonparametric.lowess(exog=itczDJF['lon'],
                                            endog=itczDJF['lat'],
                                            frac=0.05)

# use the fact that the JJA line first and last points are at 0deg latitude,
# and the fact that points were digitized as increasing downward, so need to be
# 'flipped', to correct all points' latitudes
JJA_DJF_offset = itczJJA['lat'][0] - itczDJF['lat'][0]
itczJJA['lat'] = itczJJA['lat'][0] - itczJJA['lat']
itczDJF['lat'] = itczDJF['lat'][0] - itczDJF['lat'] + JJA_DJF_offset

# rescale lon values to be between -180 and 180
rescaler = MinMaxScaler((-180, 180))
itczJJA['lon'] = rescaler.fit_transform(itczJJA['lon'].values.reshape(-1, 1))
itczDJF['lon'] = rescaler.fit_transform(itczDJF['lon'].values.reshape(-1, 1))

# add a mean ITCZ line
# NOTE: iterating over rows of itczJJA because they're slightly fewer (62 less)
mean_xs = []
mean_ys = []
for i, row in itczJJA.iterrows():
    mean_x = np.mean((row['lon'], itczDJF.iloc[i,:]['lon']))
    mean_y = np.mean((row['lat'], itczDJF.iloc[i,:]['lat']))
    mean_xs.append(mean_x)
    mean_ys.append(mean_y)
mean_coords = np.stack((mean_xs, mean_ys)).T

# drop duplicate points
itczJJA = itczJJA.drop_duplicates()
itczDJF = itczDJF.drop_duplicates()
mean_coords = pd.DataFrame(mean_coords).drop_duplicates().values

# combine into geodataframe
itczJJA_line = LineString(itczJJA.values)
itczDJF_line = LineString(itczDJF.values)
itcz_mean_line = LineString(mean_coords)
df = {'time': ['JJA', 'DJF', 'mean'], 'geometry': [itczJJA_line,
                                                   itczDJF_line,
                                                   itcz_mean_line]}
gdf = gpd.GeoDataFrame(df, crs='EPSG:4326')

# write out
gdf.to_file('ITCZ_li_zeng_2005_digitized.shp')
